version: "3.9"
services:
  bot:
    build: .
    image: mama-gpt:latest
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "6379:6379"
    restart: unless-stopped
