services:
  bot:
    build: .
    image: mama-gpt:latest
    command: ["python", "-m", "app.main"]
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      ALLOWED_USER_IDS: ${ALLOWED_USER_IDS}
      ADMIN_USER_IDS: ${ADMIN_USER_IDS}
      REPLY_PARSE_MODE: ${REPLY_PARSE_MODE:-HTML}
      HISTORY_ENABLED: ${HISTORY_ENABLED:-true}
      HISTORY_TURNS: ${HISTORY_TURNS:-6}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      METRICS_ENABLED: ${METRICS_ENABLED:-true}
      PROCESS_EDITED_MESSAGES: ${PROCESS_EDITED_MESSAGES:-false}
      DEFAULT_MODE: ${DEFAULT_MODE:-friendly}
      APP_MODE: ${APP_MODE:-polling}
      GIGACHAT_BASE_URL: ${GIGACHAT_BASE_URL}
      GIGACHAT_CHAT_PATH: ${GIGACHAT_CHAT_PATH}
      GIGACHAT_AUTH_URL: ${GIGACHAT_AUTH_URL}
      GIGACHAT_CLIENT_ID: ${GIGACHAT_CLIENT_ID}
      GIGACHAT_CLIENT_SECRET: ${GIGACHAT_CLIENT_SECRET}
      LLM_MODEL: ${LLM_MODEL}
      GIGACHAT_SCOPE: ${GIGACHAT_SCOPE}
      GIGACHAT_TOKEN_REFRESH_RESERVE: ${GIGACHAT_TOKEN_REFRESH_RESERVE:-60}
      GIGACHAT_VERIFY_SSL: ${GIGACHAT_VERIFY_SSL:-true}
      REQUEST_TIMEOUT_SEC: ${REQUEST_TIMEOUT_SEC:-60}
      CONNECT_TIMEOUT_SEC: ${CONNECT_TIMEOUT_SEC:-3}
      APP_HOST: ${APP_HOST:-0.0.0.0}
      APP_PORT: ${APP_PORT:-8080}
      UVICORN_RELOAD: ${UVICORN_RELOAD:-false}
    restart: unless-stopped
