[tool.black]
line-length = 100
target-version = ["py312"]

[tool.ruff]
line-length = 100
target-version = "py312"
select = ["E", "F", "B", "I", "N", "UP", "ASYNC"]
ignore = ["E203", "E501"]
exclude = ["venv", ".venv"]

[tool.ruff.per-file-ignores]
"tests/*" = ["D", "S101"]

[tool.mypy]
python_version = "3.12"
warn_unused_configs = true
warn_return_any = true
warn_redundant_casts = true
warn_unused_ignores = true
disallow_untyped_defs = true
disallow_any_generics = true
strict_optional = true
plugins = ["pydantic.mypy"]
